# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=64)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('web_site', models.CharField(default='Unknown', max_length=64)),
                ('date_save', models.DateTimeField(auto_now_add=True)),
                ('login_image', models.FileField(default='static/uploads/centraldb.jpeg', upload_to='static/uploads/')),
                ('slug', models.CharField(default='Unknown', max_length=64)),
                ('name_factorisation', models.CharField(default='Unknown', max_length=64)),
                ('logo_factorisation', models.FileField(default='static/uploads/centraldb.jpeg', upload_to='static/uploads/')),
                ('address_factorisation', models.CharField(default='Unknown', max_length=64)),
                ('phone', models.CharField(default='Unknown', max_length=64)),
                ('siret', models.CharField(default='Unknown', max_length=64)),
                ('ape', models.CharField(default='Unknown', max_length=64)),
                ('rcs', models.CharField(default='Unknown', max_length=64)),
                ('pref_invoice', models.CharField(default='Unknown', max_length=64)),
                ('tva_number', models.CharField(default='Unknown', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DomPeople',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_centraldb.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=64)),
                ('display_name', models.CharField(max_length=64)),
                ('link_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleToDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_centraldb.Domain')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_centraldb.Modules')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('role', models.IntegerField(choices=[(1, 'Administrateur'), (2, 'Utilisateur')], default=2)),
                ('state', models.IntegerField(default=2)),
                ('mdp', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
                ('date_last_con', models.DateTimeField(auto_now=True)),
                ('date_sign', models.DateTimeField(auto_now_add=True)),
                ('addr', models.CharField(default='unknow', max_length=64)),
                ('code_postal', models.CharField(default='unknow', max_length=64)),
                ('city', models.CharField(default='unknow', max_length=64)),
                ('is_first_connection', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='dompeople',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_centraldb.People'),
        ),
        migrations.AddField(
            model_name='contact',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='From', to='admin_centraldb.Domain'),
        ),
        migrations.AddField(
            model_name='contact',
            name='people',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='To', to='admin_centraldb.People'),
        ),
    ]
