# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_centraldb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='web_site',
            field=models.CharField(default='Unknown', max_length=64, unique=True),
        ),
    ]
