# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataplace',
            name='path_image',
            field=models.FileField(default='static/uploads/default-img', upload_to='static/uploads/'),
        ),
        migrations.AlterField(
            model_name='place',
            name='max_member',
            field=models.IntegerField(default=0),
        ),
    ]
