# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_place', '0002_auto_20171101_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadataplace',
            name='path_image',
            field=models.FileField(default='static/uploads/default-img.gif', upload_to='static/uploads/'),
        ),
    ]
